baseURL = 'https://deftdevs.com'
title = 'DEFT DEVS'
languageCode = 'en-us'
theme = "hugo-coder"
defaultcontentlanguage = "en"
paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "DEFT DEVS"
  info = "DevOps Excellence. Sustainably Delivered."
  description = "Company website"
  keywords = "company,devops,software,it,services,consulting,development,blog"
  avatarurl = "images/logo-mixed.png"
  since = 2022

  favicon_16 = "images/favicon-16.png"
  favicon_32 = "images/favicon-32.png"

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["custom.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links

# [[params.social]]
#   name = "Github"
#   icon = "fa fa-github fa-2x"
#   weight = 1
#   url = "https://github.com/deftdevs"
# [[params.social]]
#   name = "Gitlab"
#   icon = "fa fa-gitlab fa-2x"
#   weight = 2
#   url = "https://gitlab.com/deftdevs"
# [[params.social]]
#   name = "LinkedIn"
#   icon = "fa fa-linkedin fa-2x"
#   weight = 3
#   url = "https://www.linkedin.com/company/deftdevs"
# [[params.social]]
#   name = "Twitter"
#   icon = "fa fa-twitter fa-2x"
#   weight = 4
#   url = "https://twitter.com/deftdevs"

# Menu links

[[menu.main]]
  name = "Services"
  weight = 1
  url = "services/"
# [[menu.main]]
#   name = "Blog"
#   weight = 2
#   url  = "posts/"
[[menu.main]]
  name = "Contact"
  weight = 3
  url  = "contact/"
